<?php
/** JSON-driven About Us sections. @package VedCare_Divine */
$about = isset( $args['about'] ) && is_array( $args['about'] ) ? $args['about'] : array();
if ( ! $about ) { return; }
$category_images = array(
	'Mass & Weight Gain'         => array( 'assets/images/vedcare-gold.png', 'assets/images/vedcare-build.png', 'assets/images/vedcare-build-mini.png' ),
	'Fat Loss & Muscle Building' => array( 'assets/images/vedcare-lean.png' ),
	'Joint Wellness'             => array( 'assets/images/ortho-care.png' ),
);
?>
<article class="about-page">
	<section class="about-hero"><div class="container about-hero__inner"><div class="about-hero__copy"><p class="section__eyebrow"><?php echo esc_html( $about['hero']['eyebrow'] ?? '' ); ?></p><h1><?php echo esc_html( $about['hero']['heading'] ?? '' ); ?></h1><p class="about-hero__tagline"><?php echo esc_html( $about['tagline_primary'] ?? '' ); ?></p><p><?php echo esc_html( $about['tagline_secondary'] ?? '' ); ?></p></div><div class="about-hero__visual"><img src="<?php echo esc_url( vedcare_divine_asset_url( 'assets/images/about/Home-hero.png' ) ); ?>" alt="" loading="eager"></div></div></section>

	<section class="section about-who"><div class="container about-split"><div class="about-who__copy"><div class="section-heading"><h2><?php echo esc_html( $about['who_we_are']['heading'] ?? '' ); ?></h2></div><?php foreach ( (array) ( $about['who_we_are']['paragraphs'] ?? array() ) as $paragraph ) : ?><p><?php echo esc_html( $paragraph ); ?></p><?php endforeach; ?></div><div class="about-years"><img src="<?php echo esc_url( vedcare_divine_asset_url( $about['twenty_five_years']['image'] ?? '' ) ); ?>" alt="<?php echo esc_attr( $about['twenty_five_years']['heading'] ?? '' ); ?>" loading="lazy"><div><h2><?php echo esc_html( $about['twenty_five_years']['heading'] ?? '' ); ?></h2><h3><?php echo esc_html( $about['twenty_five_years']['subheading'] ?? '' ); ?></h3><?php foreach ( (array) ( $about['twenty_five_years']['paragraphs'] ?? array() ) as $paragraph ) : ?><p><?php echo esc_html( $paragraph ); ?></p><?php endforeach; ?><p class="about-highlight"><?php echo esc_html( $about['twenty_five_years']['highlight'] ?? '' ); ?></p></div></div></div></section>

	<section class="section about-belief"><div class="container about-belief__grid"><div class="about-copy"><div class="section-heading"><h2><?php echo esc_html( $about['what_we_believe']['heading'] ?? '' ); ?></h2><p class="text-lead"><?php echo esc_html( $about['what_we_believe']['subheading'] ?? '' ); ?></p></div><?php foreach ( (array) ( $about['what_we_believe']['paragraphs'] ?? array() ) as $paragraph ) : ?><p><?php echo esc_html( $paragraph ); ?></p><?php endforeach; ?><p><?php echo esc_html( $about['what_we_believe']['intro'] ?? '' ); ?></p></div><div class="about-principles"><?php foreach ( (array) ( $about['what_we_believe']['principles'] ?? array() ) as $index => $principle ) : ?><article><b><?php echo esc_html( str_pad( (string) ( $index + 1 ), 2, '0', STR_PAD_LEFT ) ); ?></b><h3><?php echo esc_html( $principle['title'] ?? '' ); ?></h3><p><?php echo esc_html( $principle['description'] ?? '' ); ?></p></article><?php endforeach; ?></div></div></section>

	<section class="section about-quality-journey"><div class="container"><div class="about-quality-journey__intro"><p class="section__eyebrow">OUR COMMITMENT TO QUALITY</p><h2>Quality Is at the Heart of Everything We Do</h2><div class="about-quality-journey__copy"><p>At VedCare Divine, quality is at the heart of everything we do.</p><p>Our products are manufactured by Tasmai Nutraceuticals, with a dedicated focus on maintaining consistency and quality throughout the manufacturing process.</p><p>We have our own Research &amp; Development (R&amp;D) team that supports product development and continuous improvement.</p><p>Before a product reaches the customer, each batch undergoes quality checks before packaging. This quality-focused process helps us maintain consistency and gives us greater confidence in the products we deliver.</p></div></div><div class="about-quality-journey__process"><h3>Our Quality Journey</h3><ol><li><span>01</span><p>Research &amp; Development</p></li><li><span>02</span><p>Formulation &amp; Product Development</p></li><li><span>03</span><p>Manufacturing by Tasmai Nutraceuticals</p></li><li><span>04</span><p>Batch-wise Quality Check</p></li><li><span>05</span><p>Careful Packaging</p></li></ol></div></div></section>

	<section class="section why-section about-commitment-section"><div class="container"><div class="section-heading section-heading--center"><h2><?php echo esc_html( $about['our_commitment']['heading'] ?? '' ); ?></h2><p class="text-lead"><?php echo esc_html( $about['our_commitment']['subheading'] ?? '' ); ?></p></div><div class="about-commitment"><?php foreach ( (array) ( $about['our_commitment']['items'] ?? array() ) as $index => $item ) : ?><article><b><?php echo esc_html( str_pad( (string) ( $index + 1 ), 2, '0', STR_PAD_LEFT ) ); ?></b><h3><?php echo esc_html( $item['title'] ?? '' ); ?></h3><p><?php echo esc_html( $item['description'] ?? '' ); ?></p></article><?php endforeach; ?></div></div></section>

	<section class="section about-wellness"><div class="container about-wellness__grid"><div class="about-copy"><div class="section-heading"><h2><?php echo esc_html( $about['wellness_approach']['heading'] ?? '' ); ?></h2><p class="text-lead"><?php echo esc_html( $about['wellness_approach']['subheading'] ?? '' ); ?></p></div><?php foreach ( (array) ( $about['wellness_approach']['paragraphs'] ?? array() ) as $paragraph ) : ?><p><?php echo esc_html( $paragraph ); ?></p><?php endforeach; ?><?php if ( ! empty( $about['wellness_approach']['cta']['label'] ) ) : ?><p class="about-actions"><a class="button button--secondary" href="<?php echo esc_url( home_url( '/#bestsellers' ) ); ?>"><?php echo esc_html( $about['wellness_approach']['cta']['label'] ); ?></a></p><?php endif; ?></div><div class="about-categories"><?php foreach ( (array) ( $about['wellness_approach']['categories'] ?? array() ) as $category ) : ?><?php $images = $category_images[ $category['title'] ?? '' ] ?? array(); ?><article><div class="about-categories__images"><?php foreach ( $images as $image ) : ?><img src="<?php echo esc_url( vedcare_divine_asset_url( $image ) ); ?>" alt="" loading="lazy"><?php endforeach; ?></div><h3><?php echo esc_html( $category['title'] ?? '' ); ?></h3><p><?php echo esc_html( implode( ' • ', (array) ( $category['products'] ?? array() ) ) ); ?></p></article><?php endforeach; ?></div></div></section>

	<section class="section about-quality"><div class="container about-quality__inner"><div><div class="section-heading"><h2><?php echo esc_html( $about['quality_consistency']['heading'] ?? '' ); ?></h2><p class="text-lead"><?php echo esc_html( $about['quality_consistency']['subheading'] ?? '' ); ?></p></div><?php foreach ( (array) ( $about['quality_consistency']['paragraphs'] ?? array() ) as $paragraph ) : ?><p><?php echo esc_html( $paragraph ); ?></p><?php endforeach; ?><p class="about-highlight"><?php echo esc_html( $about['quality_consistency']['brand_statement'] ?? '' ); ?></p></div><img src="<?php echo esc_url( vedcare_divine_asset_url( 'assets/images/about/Home-hero.png' ) ); ?>" alt="" loading="lazy"></div></section>

	<section class="section about-journey"><div class="container about-journey__grid"><img src="<?php echo esc_url( vedcare_divine_asset_url( $about['twenty_five_years']['image'] ?? '' ) ); ?>" alt="" loading="lazy"><div class="about-copy"><div class="section-heading"><h2><?php echo esc_html( $about['journey_continues']['heading'] ?? '' ); ?></h2><p class="text-lead"><?php echo esc_html( $about['journey_continues']['subheading'] ?? '' ); ?></p></div><?php foreach ( (array) ( $about['journey_continues']['paragraphs'] ?? array() ) as $paragraph ) : ?><p><?php echo esc_html( $paragraph ); ?></p><?php endforeach; ?><p class="about-highlight"><?php echo esc_html( $about['journey_continues']['highlight'] ?? '' ); ?></p><p><?php echo esc_html( $about['journey_continues']['closing'] ?? '' ); ?></p><?php if ( ! empty( $about['product_guidance']['cta']['label'] ) ) : ?><p class="about-actions"><a class="button button--secondary" href="<?php echo esc_url( home_url( $about['product_guidance']['cta']['url'] ?? '/' ) ); ?>"><?php echo esc_html( $about['product_guidance']['cta']['label'] ); ?></a></p><?php endif; ?></div></div></section>

	<section class="section about-final-cta"><div class="container about-final-cta__inner"><div><p class="section__eyebrow"><?php echo esc_html( $about['product_guidance']['subheading'] ?? '' ); ?></p><h2><?php echo esc_html( $about['product_guidance']['heading'] ?? '' ); ?></h2><p><?php echo esc_html( $about['product_guidance']['text'] ?? '' ); ?></p></div><?php if ( ! empty( $about['product_guidance']['cta']['label'] ) ) : ?><a class="button button--gold" href="<?php echo esc_url( home_url( $about['product_guidance']['cta']['url'] ?? '/' ) ); ?>"><?php echo esc_html( $about['product_guidance']['cta']['label'] ); ?></a><?php endif; ?></div></section>
</article>
