<?php
/** JSON-driven product page sections. @package VedCare_Divine */
$product = isset( $args['product'] ) && is_array( $args['product'] ) ? $args['product'] : array();
if ( ! $product ) { return; }
$currency = static function( $amount ) { return is_numeric( $amount ) ? '₹' . number_format_i18n( (float) $amount ) : ''; };
$video_embed_url = static function( $url ) { return preg_match( '#(?:youtu\.be/|youtube\.com/(?:watch\?v=|shorts/))([A-Za-z0-9_-]{11})#', $url, $matches ) ? 'https://www.youtube.com/embed/' . $matches[1] : ''; };
$product_image = ! empty( $product['product_image'] ) ? $product['product_image'] : '';
$gallery_images = array_values( array_filter( (array) ( $product['gallery_images'] ?? array() ) ) );
if ( $gallery_images ) { $product_image = $gallery_images[0]; }
$wc_product_id = absint( $product['woocommerce']['product_id'] ?? 0 );
$purchase_url  = $wc_product_id && function_exists( 'wc_get_product' ) && wc_get_product( $wc_product_id ) ? add_query_arg( 'add-to-cart', $wc_product_id, home_url( '/' ) ) : vedcare_divine_shop_url();
$testimonials  = array();
$testimonial_file = get_theme_file_path( 'assets/data/testimonials.json' );
if ( is_readable( $testimonial_file ) ) {
	$testimonial_data = json_decode( file_get_contents( $testimonial_file ), true ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	$filter_product = strtolower( trim( $product['testimonials']['filter_product'] ?? '' ) );
	$weight_gain_products = array( 'vedcare gold', 'vedcare build', 'vedcare build mini' );
	$is_weight_gain_product = in_array( strtolower( trim( $product['name'] ?? '' ) ), $weight_gain_products, true );
	foreach ( is_array( $testimonial_data ) ? $testimonial_data : array() as $testimonial ) {
		$testimonial_product = strtolower( trim( $testimonial['product'] ?? '' ) );
		$matches_product = $is_weight_gain_product
			? in_array( $testimonial_product, array( 'vedcare gold', 'vedcare build' ), true )
			: $filter_product === $testimonial_product;
		if ( is_array( $testimonial ) && ! empty( $testimonial['active'] ) && $matches_product && ! empty( $testimonial['image'] ) && is_readable( get_theme_file_path( 'assets/images/testimonials/' . sanitize_file_name( $testimonial['image'] ) ) ) ) { $testimonials[] = $testimonial; }
	}
}
$testimonial_count = count( $testimonials );
$testimonial_rating = $testimonial_count ? array_sum( array_map( static function( $testimonial ) { return absint( $testimonial['rating'] ?? 0 ); }, $testimonials ) ) / $testimonial_count : 0;
$benefits = array_values( array_filter( (array) ( $product['benefits'] ?? array() ), static function( $benefit ) { return false === strpos( (string) $benefit, 'where supported by official documentation' ); } ) );
$rating_value = absint( $product['rating']['value'] ?? 0 );
$customer_count_label = trim( (string) ( $product['rating']['customer_count_label'] ?? '' ) );
$transformation_images = array();
$transformation_file = get_theme_file_path( 'assets/data/transformations.json' );
if ( is_readable( $transformation_file ) ) { $transformation_data = json_decode( file_get_contents( $transformation_file ), true ); $transformation_images = array_values( array_filter( (array) ( $transformation_data[ $product['product_id'] ?? '' ] ?? array() ), static function( $image ) { return is_string( $image ) && is_readable( get_theme_file_path( $image ) ); } ) ); }
?>
<script>window.vedcareProductGallery=<?php echo wp_json_encode( array( 'images' => array_map( 'vedcare_divine_asset_url', $gallery_images ), 'highlights' => (array) ( $product['hero_highlights'] ?? array() ), 'ingredients' => array_map( static function( $item ) { return ! empty( $item['image'] ) ? vedcare_divine_asset_url( $item['image'] ) : ''; }, (array) ( $product['key_ingredients'] ?? array() ) ), 'hindi_benefits' => array_values( array_filter( (array) ( $product['hindi_benefits'] ?? array() ) ) ) ) ); ?>;</script>
<article class="product-page">
	<section class="product-hero"><div class="container product-hero__grid"><div class="product-hero__visual"><div class="product-hero__thumbnail"><?php if ( $product_image ) : ?><img src="<?php echo esc_url( vedcare_divine_asset_url( $product_image ) ); ?>" alt="" loading="eager"><?php endif; ?></div><div class="product-hero__highlights"><?php if ( ! empty( $product['herb_count'] ) ) : ?><span><b><?php echo esc_html( absint( $product['herb_count'] ) ); ?></b><small><?php esc_html_e( 'Herbs', 'vedcare-divine' ); ?></small></span><?php endif; ?><?php if ( ! empty( $product['pack_duration'] ) ) : ?><span><b><?php echo esc_html( $product['pack_duration'] ); ?></b><small><?php esc_html_e( 'Pack duration', 'vedcare-divine' ); ?></small></span><?php endif; ?><?php if ( ! empty( $product['net_quantity_g'] ) ) : ?><span><b><?php echo esc_html( absint( $product['net_quantity_g'] ) . ' g' ); ?></b><small><?php esc_html_e( 'Net quantity', 'vedcare-divine' ); ?></small></span><?php endif; ?></div><?php if ( $product_image ) : ?><img class="product-hero__image" src="<?php echo esc_url( vedcare_divine_asset_url( $product_image ) ); ?>" alt="<?php echo esc_attr( $product['name'] ?? '' ); ?>"><?php endif; ?></div><div class="product-hero__content"><p class="section__eyebrow"><?php echo esc_html( $product['category'] ?? '' ); ?></p><h1><?php echo esc_html( $product['name'] ?? '' ); ?></h1><p class="product-hero__positioning"><?php echo esc_html( $product['positioning'] ?? '' ); ?></p><?php if ( $rating_value && $customer_count_label ) : ?><p class="product-hero__rating"><span aria-label="<?php echo esc_attr( sprintf( __( '%d out of 5 stars', 'vedcare-divine' ), $rating_value ) ); ?>"><?php echo esc_html( str_repeat( '★', min( 5, $rating_value ) ) ); ?></span> <?php echo esc_html( $customer_count_label ); ?></p><?php endif; ?><p class="product-hero__herbs"><?php echo esc_html( sprintf( __( '%d herbs', 'vedcare-divine' ), absint( $product['herb_count'] ?? 0 ) ) ); ?></p><p class="product-hero__price"><strong><?php echo esc_html( $currency( $product['offer_price_inr'] ?? null ) ); ?></strong><?php if ( ! empty( $product['mrp_inr'] ) ) : ?> <del><?php echo esc_html( $currency( $product['mrp_inr'] ) ); ?></del><?php endif; ?></p><label class="product-hero__quantity"><?php esc_html_e( 'Quantity', 'vedcare-divine' ); ?><input id="vedcare-product-quantity" type="number" min="1" value="1" aria-label="<?php esc_attr_e( 'Quantity', 'vedcare-divine' ); ?>"></label><div class="product-hero__actions"><a class="button button--gold" href="<?php echo esc_url( $purchase_url ); ?>"><?php esc_html_e( 'Buy now', 'vedcare-divine' ); ?></a><a class="button button--secondary" href="<?php echo esc_url( $purchase_url ); ?>"><?php esc_html_e( 'Add to cart', 'vedcare-divine' ); ?></a></div></div></div></section>

	<section class="product-benefits"><div class="container"><div class="product-benefits__grid"><?php foreach ( array_slice( $benefits, 0, 5 ) as $benefit ) : ?><div><span aria-hidden="true">✦</span><p><?php echo esc_html( $benefit ); ?></p></div><?php endforeach; ?></div></div></section>

	<?php if ( $transformation_images ) : ?><section class="section product-transformations"><div class="container"><div class="section-heading section-heading--center"><h2><?php esc_html_e( 'Transformation Photos', 'vedcare-divine' ); ?></h2></div><div class="transformations-carousel" tabindex="0"><div class="transformations-carousel__viewport"><div class="transformations-carousel__track"><?php foreach ( $transformation_images as $index => $image ) : ?><button class="transformations-carousel__slide" type="button" data-transformation-index="<?php echo esc_attr( $index ); ?>"><img src="<?php echo esc_url( vedcare_divine_asset_url( $image ) ); ?>" alt="" loading="lazy"></button><?php endforeach; ?></div></div><button class="transformations-carousel__button transformations-carousel__button--previous" type="button" aria-label="<?php esc_attr_e( 'Previous transformation photos', 'vedcare-divine' ); ?>">‹</button><button class="transformations-carousel__button transformations-carousel__button--next" type="button" aria-label="<?php esc_attr_e( 'Next transformation photos', 'vedcare-divine' ); ?>">›</button></div></div></section><dialog class="transformations-lightbox" aria-label="<?php esc_attr_e( 'Transformation photo viewer', 'vedcare-divine' ); ?>"><button type="button" class="transformations-lightbox__close" aria-label="<?php esc_attr_e( 'Close viewer', 'vedcare-divine' ); ?>">×</button><button type="button" class="transformations-lightbox__previous" aria-label="<?php esc_attr_e( 'Previous photo', 'vedcare-divine' ); ?>">‹</button><img src="" alt=""><button type="button" class="transformations-lightbox__next" aria-label="<?php esc_attr_e( 'Next photo', 'vedcare-divine' ); ?>">›</button></dialog><?php endif; ?>

	<section class="section product-details"><div class="container product-details__grid"><div><p class="section__eyebrow"><?php esc_html_e( 'Product details', 'vedcare-divine' ); ?></p><h2><?php esc_html_e( 'Complete Benefits', 'vedcare-divine' ); ?></h2><ul class="product-list"><?php foreach ( $benefits as $benefit ) : ?><li><?php echo esc_html( $benefit ); ?></li><?php endforeach; ?></ul></div><div><p class="section__eyebrow"><?php esc_html_e( 'Ingredients', 'vedcare-divine' ); ?></p><h2><?php echo esc_html( sprintf( __( 'Key Ingredients (%d Herbs)', 'vedcare-divine' ), absint( $product['herb_count'] ?? 0 ) ) ); ?></h2><div class="ingredients-grid"><?php foreach ( (array) ( $product['key_ingredients'] ?? array() ) as $ingredient ) : ?><article><h3><?php echo esc_html( $ingredient['name'] ?? '' ); ?></h3><p><?php echo esc_html( $ingredient['botanical_name'] ?? '' ); ?></p><?php if ( isset( $ingredient['amount_mg'] ) ) : ?><small><?php echo esc_html( absint( $ingredient['amount_mg'] ) . ' mg' ); ?></small><?php endif; ?></article><?php endforeach; ?><?php $additional_herbs = max( 0, absint( $product['herb_count'] ?? 0 ) - count( (array) ( $product['key_ingredients'] ?? array() ) ) ); if ( $additional_herbs ) : ?><article class="ingredients-grid__more"><b>+<?php echo esc_html( $additional_herbs ); ?></b><p><?php esc_html_e( 'More Herbs', 'vedcare-divine' ); ?></p></article><?php endif; ?></div><button class="button button--secondary product-details__ingredients-link" type="button" data-ingredient-modal-open><?php esc_html_e( 'View full ingredient list', 'vedcare-divine' ); ?></button><div class="product-details__how-to-use"><h2><?php esc_html_e( 'How to Use', 'vedcare-divine' ); ?></h2><dl class="product-definition-list"><?php foreach ( array( __( 'Dose', 'vedcare-divine' ) => $product['how_to_use']['dose'] ?? '', __( 'Directions', 'vedcare-divine' ) => $product['how_to_use']['directions'] ?? '', __( 'Timing', 'vedcare-divine' ) => $product['how_to_use']['timing'] ?? '' ) as $label => $value ) : ?><?php if ( $value ) : ?><dt><?php echo esc_html( $label ); ?></dt><dd><?php echo esc_html( $value ); ?></dd><?php endif; ?><?php endforeach; ?></dl><?php if ( ! empty( $product['precautions'] ) ) : ?><h3><?php esc_html_e( 'Precautions', 'vedcare-divine' ); ?></h3><ul class="product-list product-list--compact"><?php foreach ( (array) $product['precautions'] as $precaution ) : ?><li><?php echo esc_html( $precaution ); ?></li><?php endforeach; ?></ul><?php endif; ?></div></div></div></section>


	<section class="section product-videos"><div class="container"><div class="section-heading section-heading--center"><p class="section__eyebrow"><?php esc_html_e( 'Learn more', 'vedcare-divine' ); ?></p><h2><?php esc_html_e( 'Product Videos', 'vedcare-divine' ); ?></h2></div><div class="product-videos__grid"><?php foreach ( array( __( 'Information Video', 'vedcare-divine' ) => $product['videos']['information'] ?? '', __( 'Transformation Video', 'vedcare-divine' ) => $product['videos']['transformation'] ?? '' ) as $title => $url ) : ?><?php if ( $url ) : ?><?php $embed_url = $video_embed_url( $url ); ?><article><h3><?php echo esc_html( $title ); ?></h3><?php if ( $embed_url ) : ?><iframe src="<?php echo esc_url( $embed_url ); ?>" title="<?php echo esc_attr( $title ); ?>" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><?php else : ?><a href="<?php echo esc_url( $url ); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Watch video', 'vedcare-divine' ); ?></a><?php endif; ?></article><?php endif; ?><?php endforeach; ?></div></div></section>

	<?php if ( $testimonials ) : ?><section class="section product-testimonials"><div class="container"><div class="section-heading section-heading--center"><p class="section__eyebrow"><?php esc_html_e( 'Customer stories', 'vedcare-divine' ); ?></p><h2><?php esc_html_e( 'Real Results. Real Experiences.', 'vedcare-divine' ); ?></h2></div><section class="testimonials-carousel" aria-roledescription="carousel" aria-label="<?php esc_attr_e( 'Product testimonials', 'vedcare-divine' ); ?>" tabindex="0"><div class="testimonials-carousel__viewport"><div class="testimonials-carousel__track"><?php foreach ( $testimonials as $testimonial ) : ?><article class="story-card testimonials-carousel__slide" role="group" aria-roledescription="slide"><img src="<?php echo esc_url( vedcare_divine_asset_url( 'assets/images/testimonials/' . sanitize_file_name( $testimonial['image'] ) ) ); ?>" alt="<?php echo esc_attr( $testimonial['name'] ?? '' ); ?>" loading="lazy"><div><div class="story-card__meta"><h3><?php echo esc_html( $testimonial['name'] ?? '' ); ?></h3><p><?php echo esc_html( $testimonial['location'] ?? '' ); ?></p></div><p class="story-card__rating" aria-label="<?php echo esc_attr( sprintf( __( '%d out of 5 stars', 'vedcare-divine' ), absint( $testimonial['rating'] ?? 0 ) ) ); ?>"><?php echo esc_html( str_repeat( '★', min( 5, absint( $testimonial['rating'] ?? 0 ) ) ) ); ?></p><p class="story-card__comment"><?php echo esc_html( str_replace( '{product_name}', $product['name'] ?? '', $testimonial['comment'] ?? '' ) ); ?></p></div></article><?php endforeach; ?></div></div><button class="testimonials-carousel__button testimonials-carousel__button--previous" type="button" aria-label="<?php esc_attr_e( 'Previous testimonials', 'vedcare-divine' ); ?>">‹</button><button class="testimonials-carousel__button testimonials-carousel__button--next" type="button" aria-label="<?php esc_attr_e( 'Next testimonials', 'vedcare-divine' ); ?>">›</button><div class="testimonials-carousel__pagination" role="group" aria-label="<?php esc_attr_e( 'Choose testimonials', 'vedcare-divine' ); ?>"></div></section></div></section><?php endif; ?>

	<section class="section product-quality"><div class="container"><div class="section-heading section-heading--center"><p class="section__eyebrow"><?php esc_html_e( 'Quality & documentation', 'vedcare-divine' ); ?></p><h2><?php esc_html_e( 'Quality You Can Trust', 'vedcare-divine' ); ?></h2></div><div class="quality-seals"><?php for ( $seal = 1; $seal <= 6; $seal++ ) : ?><img src="<?php echo esc_url( vedcare_divine_asset_url( 'assets/images/certifications/certificate-seal-' . $seal . '.png.png' ) ); ?>" alt="" loading="lazy"><?php endfor; ?></div></div></section>

	<section class="product-guidance"><div class="container product-guidance__inner"><div><p class="section__eyebrow"><?php esc_html_e( 'Personal guidance', 'vedcare-divine' ); ?></p><h2><?php esc_html_e( 'Not Sure if This Product Is Right for You?', 'vedcare-divine' ); ?></h2></div><div><a class="button button--gold" href="<?php echo esc_url( $purchase_url ); ?>"><?php esc_html_e( 'Buy now', 'vedcare-divine' ); ?></a><a class="button button--outline-light" href="https://wa.me/919577377737" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Talk to an expert', 'vedcare-divine' ); ?></a></div></div></section>
	<div class="product-purchase-bar"><div class="container"><span><?php echo esc_html( $product['name'] ?? '' ); ?> <strong><?php echo esc_html( $currency( $product['offer_price_inr'] ?? null ) ); ?></strong></span><a class="button button--gold" href="<?php echo esc_url( $purchase_url ); ?>"><?php esc_html_e( 'Buy now', 'vedcare-divine' ); ?></a><a class="button button--outline-light" href="https://wa.me/919577377737" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Talk to an expert', 'vedcare-divine' ); ?></a></div></div>
<dialog class="ingredient-modal" aria-labelledby="ingredient-modal-title"><div class="ingredient-modal__content"><button class="ingredient-modal__close" type="button" data-ingredient-modal-close aria-label="<?php esc_attr_e( 'Close ingredient list', 'vedcare-divine' ); ?>">×</button><h2 id="ingredient-modal-title"><?php esc_html_e( 'Full Ingredient List', 'vedcare-divine' ); ?></h2><ul class="product-list product-list--compact"><?php foreach ( (array) ( $product['additional_documented_ingredients'] ?? array() ) as $ingredient ) : ?><li><?php echo esc_html( $ingredient ); ?></li><?php endforeach; ?></ul></div></dialog>
</article>
